version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rugbY46
      POSTGRES_DB: pokerallline
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgresql://admin:rugbY46@db:5432/pokerallline
    depends_on:
      - db

volumes:
  db_data: